# -*- coding: utf-8 -*-
"""Fine_Tuning_Mistral7B_Q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAQU6u1EIAmDUmBiDrgNbR-taif3U4z2
"""

# !pip install bitsandbytes evaluate

from huggingface_hub import login

HF_TOKEN = "..." # replace with your own HuggingFace Token

if HF_TOKEN:
    login(HF_TOKEN)
    print("Successfully logged in to Hugging Face!")
else:
    print("Token is not set. Please set your HF_TOKEN.")

import json
import hashlib
import random
import os
import torch.nn as nn
import pandas as pd
import functools
import numpy as np
import torch
import shutil
import evaluate
import math
import gc, sys
from tqdm import tqdm
from collections import defaultdict
from datasets import load_from_disk
from dataclasses import dataclass
import torch.nn.functional as F
from torch.nn.functional import softmax
from torch.utils.data import DataLoader
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, AutoModelForSequenceClassification, TrainerCallback, TrainerControl, TrainerState, Trainer, BitsAndBytesConfig, DataCollatorWithPadding, AutoConfig, PreTrainedTokenizerBase
from transformers.trainer_utils import IntervalStrategy
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model, PeftModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
import matplotlib.pyplot as plt

with open("challenge_data.json", "r") as f:
    data = json.load(f)

texts = [item["conversation_text"].strip() for item in data]
intents = [item["intent"] for item in data]

le = LabelEncoder()
int_labels = le.fit_transform(intents)

label_names = le.classes_.tolist()
label_path = "label_names.json"
with open(label_path, "w") as f:
    json.dump(label_names, f, indent=2)

x_train, x_val, y_train, y_val = train_test_split(
    texts, int_labels, test_size=0.1, stratify=int_labels, random_state=42
)

ds = DatasetDict({
    "train": Dataset.from_dict({"text": x_train, "labels": y_train}),
    "val": Dataset.from_dict({"text": x_val, "labels": y_val}),
})

print(ds)
print(ds["train"][0])

model_name = 'mistralai/Mistral-7B-v0.1'

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

texts = ds["train"]["text"][:] + ds["val"]["text"][:]

lengths = [len(tokenizer(text, truncation=False, add_special_tokens=True)["input_ids"]) for text in texts]

print(f"Max length: {max(lengths)}")
print(f"Mean length: {np.mean(lengths):.2f}")
print(f"Median length: {np.median(lengths)}")
print(f"95th percentile: {np.percentile(lengths, 95)}")
print(f"99th percentile: {np.percentile(lengths, 99)}")

def tokenize_examples(examples, tokenizer):
    tokenized = tokenizer(examples['text'], truncation=True, padding="max_length", max_length=1024)
    tokenized['labels'] = examples['labels']
    return tokenized

tokenized_ds = ds.map(functools.partial(tokenize_examples, tokenizer=tokenizer), batched=True)
tokenized_ds = tokenized_ds.with_format('torch')

# qunatization config
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

# lora config
lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.1,
    bias='none',
    task_type='SEQ_CLS'
)

# load model
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    num_labels=len(label_names)
)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)
model.config.pad_token_id = tokenizer.pad_token_id

def collate_fn(batch, tokenizer):
    input_ids = [item['input_ids'] for item in batch]
    attention_mask = [item['attention_mask'] for item in batch]
    labels = torch.tensor([item['labels'] for item in batch], dtype=torch.long)

    input_ids = torch.nn.utils.rnn.pad_sequence(input_ids, batch_first=True, padding_value=tokenizer.pad_token_id)
    attention_mask = torch.nn.utils.rnn.pad_sequence(attention_mask, batch_first=True, padding_value=0)

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

from sklearn.metrics import f1_score, accuracy_score

def compute_metrics(p):
    preds = torch.argmax(torch.tensor(p.predictions), dim=1).numpy()
    labels = p.label_ids
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_micro": f1_score(labels, preds, average="micro"),
        "f1_macro": f1_score(labels, preds, average="macro")
    }

class LoggingCallback(TrainerCallback):
    def __init__(self):
        self.logs = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            entry = {"step": state.global_step}
            entry.update({k: v for k, v in logs.items()})
            self.logs.append(entry)
            print(f"Step {state.global_step} | Logs: {logs}")

training_args = TrainingArguments(
    output_dir="intent_classification",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    optim="paged_adamw_32bit",
    save_strategy="epoch",
    eval_strategy="epoch",
    logging_strategy="steps",
    logging_steps=5,
    max_grad_norm=1.0,
    warmup_ratio=0.1,
    group_by_length=True,
    lr_scheduler_type="linear",
    report_to="none",
    disable_tqdm=False,
    bf16=True,
    save_total_limit=2,
    learning_rate = 2e-5,
    per_device_eval_batch_size = 8,
    weight_decay = 0.01
)

logging_callback = LoggingCallback()

trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_ds["train"],
    eval_dataset = tokenized_ds["val"],
    tokenizer = tokenizer,
    data_collator = functools.partial(collate_fn, tokenizer=tokenizer),
    compute_metrics = compute_metrics,
    callbacks=[logging_callback]
)

trainer.train()

log_df = pd.DataFrame(logging_callback.logs)

train_df = log_df[log_df["loss"].notna()]

plt.figure(figsize=(8,5))
plt.plot(train_df["step"], train_df["loss"], label="Training Loss")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.title("Mistral 7B Training & Eval Loss")
plt.legend()
plt.grid(True, alpha=0.5)
plt.show()

if "grad_norm" in log_df:
    grad_df = log_df[log_df["grad_norm"].notna()]
    plt.figure(figsize=(8,5))
    plt.plot(grad_df["step"], grad_df["grad_norm"], color="orange", label="Grad Norm")
    plt.xlabel("Step")
    plt.ylabel("Gradient Norm")
    plt.title("Mistral 7B Gradient Norm")
    plt.legend()
    plt.grid(True, alpha=0.5)
    plt.show()

predictions = trainer.predict(tokenized_ds["val"])
y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=-1)

print("Fine-Tuned Mistral 7B 4bit Classification Report:\n")
print(classification_report(y_true, y_pred, digits=4))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()